# === CONFIGURAÇÃO DO BANCO DE DADOS (DOCKER) ===
spring.datasource.url=jdbc:mysql://localhost:3306/wa10_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# === CONFIGURAÇÃO DO MAILPIT (DOCKER) ===
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.frontend.url=${WA10_FRONTEND_URL:https://wa10-portal.onrender.com}
